cicd:
- any:
	- changed-files:
		- any-glob-to-any-file:
			- ".github/*"
aws:
- any:
	- changed-files:
		- any-glob-to-any-file:
			- "aws/*"
doc:
- any:
	- changed-files:
		- any-glob-to-any-file:
			- "**/*.md"
			- "**/*.doc"
