---
Description: using parameter and output
Parameters:
  Name:
    Description: String type parameter
    Type: String
    Default: Peter
    MinLength: 3
    MaxLength: 30
  Season:
    Description: Discrete value parameter
    Type:
    Defaut: Summer
    AllowedValues:
      - Spring
      - Summer
      - Autumn
      - Winter
  Coin:
    Description: Numeric value parameter
    Type: Number
    Default: 7
    MinValue: -3
    MaxValue: 105

Outputs:
  Val1:
    Description: An output value
    Value: Coin
    Export:
      Name: CoinCount
  Val2:
    Value: !Ref Queue

Resources:
  Queue:
    Type: AWS::SQS::Queue
    Properties:
      Tags:
        - Key: Name
          Value: by-cloud-formation
        - Key: CloudFormation
          Value: true
