---
Description: using parameter
Parameters:
Outputs:
Resrouces:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 192.168.0.0/20
      Tags:
      - Key: Name
        Value: by-cloud-formation
      - Key: CloudFormation
        Value: true
