---
name: Lint

on:
  pull_request:
    types:
    - opened
    - reopened
    - synchronize

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Lint yml files
      uses: karancode/yamllint-github-action@v2.0.0
      with:
        yamllint_file_or_dir: .
        yamllint_config_filepath: .yamllint.yml
